name: Update HKID Count

on:
  push:
    paths:
      - hkid_count.txt
  workflow_dispatch:

jobs:
  update-count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch current HKID count
        run: |
          current_count=$(cat hkid_count.txt)
          echo "Current HKID count: $current_count"
        id: fetch_count

      - name: Update HKID count
        env:
          GH_TOKEN: ${{ secrets.MY_TOKEN_HKID_COUNT }}
        run: |
          new_count=$(( $(cat hkid_count.txt) + 1 )) # Example increment logic
          echo "New HKID count: $new_count"
          
          if [ "$new_count" != "$(cat hkid_count.txt)" ]; then
            echo "$new_count" > hkid_count.txt
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add hkid_count.txt
            git commit -m "Update HKID count"
            git push
          else
            echo "No change in HKID count. Skipping commit and push."
          fi
